# Generated by Django 4.0.1 on 2022-02-27 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('ST', 'Starter'), ('MA', 'Main'), ('DE', 'DE')], default='ST', max_length=2)),
                ('name', models.CharField(max_length=150)),
                ('diet', models.CharField(blank=True, choices=[('ME', 'Meat'), ('FI', 'Fish'), ('VE', 'Vegetarian')], max_length=2)),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
    ]
