# Generated by Django 4.0.1 on 2022-02-27 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_dish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('time', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('customer', models.ForeignKey(default=2113238626640, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dessert', models.ForeignKey(limit_choices_to={'course': 'DE'}, on_delete=django.db.models.deletion.PROTECT, related_name='dessert', to='menu.dish')),
                ('main', models.ForeignKey(limit_choices_to={'course': 'MA'}, on_delete=django.db.models.deletion.PROTECT, related_name='main', to='menu.dish')),
                ('starter', models.ForeignKey(limit_choices_to={'course': 'ST'}, on_delete=django.db.models.deletion.PROTECT, related_name='starter', to='menu.dish')),
            ],
        ),
    ]
