# Generated by Django 4.0.1 on 2022-02-28 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_alter_order_customer_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=2048279199264, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='dessert',
            field=models.ForeignKey(blank=True, limit_choices_to={'course': 'DE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dessert', to='menu.dish'),
        ),
        migrations.AlterField(
            model_name='order',
            name='main',
            field=models.ForeignKey(blank=True, limit_choices_to={'course': 'MA'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main', to='menu.dish'),
        ),
        migrations.AlterField(
            model_name='order',
            name='starter',
            field=models.ForeignKey(blank=True, limit_choices_to={'course': 'ST'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='starter', to='menu.dish'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('PE', 'Pending'), ('DE', 'Out for Delivery'), ('CO', 'Order Complete')], max_length=2),
        ),
    ]
