# Generated by Django 4.0.1 on 2022-03-03 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_alter_order_customer_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('OR', 'Ordering'), ('PE', 'Pending'), ('DL', 'Out for Delivery'), ('LL', 'Ready for Collection'), ('CO', 'Order Complete')], default='Y', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(db_constraint=False, default=2597532886496, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OR', 'Ordering'), ('PE', 'Pending'), ('DL', 'Out for Delivery'), ('LL', 'Ready for Collection'), ('CO', 'Order Complete')], default='OR', max_length=2),
        ),
    ]
