# Generated by Django 4.0.1 on 2022-03-04 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=1722321822800, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='dessert',
            field=models.ForeignKey(blank=True, limit_choices_to={'course': 'DE'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dessert', to='menu.dish'),
        ),
        migrations.AlterField(
            model_name='order',
            name='main',
            field=models.ForeignKey(blank=True, limit_choices_to={'course': 'MA'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main', to='menu.dish'),
        ),
        migrations.AlterField(
            model_name='order',
            name='starter',
            field=models.ForeignKey(blank=True, limit_choices_to={'course': 'ST'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='starter', to='menu.dish'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OR', 'Ordering'), ('PE', 'Pending'), ('DL', 'Out for Delivery'), ('CL', 'Ready for Collection'), ('CO', 'Complete')], default='OR', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
