# Generated by Django 4.0.1 on 2022-03-05 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0022_alter_order_customer_alter_order_dessert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='course',
            field=models.CharField(choices=[('EM', ' '), ('ST', 'Starter'), ('MA', 'Main'), ('DE', 'Dessert')], default='ST', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=1315803715280, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('DL', 'Delivery'), ('CL', 'Collection')], default='DL', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='dessert',
            field=models.ForeignKey(default=1315761946864, limit_choices_to={'course': 'EM'}, on_delete=django.db.models.deletion.CASCADE, related_name='dessert', to='menu.dish'),
        ),
        migrations.AlterField(
            model_name='order',
            name='main',
            field=models.ForeignKey(default=1315761946864, limit_choices_to={'course': 'EM'}, on_delete=django.db.models.deletion.CASCADE, related_name='main', to='menu.dish'),
        ),
        migrations.AlterField(
            model_name='order',
            name='starter',
            field=models.ForeignKey(default=1315761946864, limit_choices_to={'course': 'EM'}, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='starter', to='menu.dish'),
        ),
    ]
